name: firstworkflow
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "welcome"
